packages:
  - 'apps/*'
  - 'lib/*'

catalog:
  '@tanstack/react-query': ^5.90.21
  '@types/node': ^25.3.3
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  react: 19.1.0
  react-dom: 19.1.0
  zod: ^3.25.76
